title: FeliX
description: Documentation for the FeliX Model
# remote_theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
url: ""

# logo: "/images/iiasa_png logo_blue.png"

search_enabled: false

aux_links:
  "FeliX model on GitHub":
    - "https://github.com/iiasa/Felix-Model"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

math: katex

footer_content: "footer"

