title: FeliX
description: Documentation for the FeliX Model
remote_theme: just-the-docs

url: https://iiasa.github.io/felix_docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
